[workspace]
members = [
"my_noir",
"hello_world",
"native_balance",
"token_balance",
"prove_hist_punk_ownership",
"prove_hist_punk_ownership2",
"prove_eoa_activity",
"prove_eoa_activity2",
"state_proof",
"storage_proof"
]
